<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aedbserver" failures="2" tests="2" name="com.ae.qa.testcasesWorkflowAdmin.CataloguePageTestWA" time="96.516" errors="0" timestamp="2023-04-18T18:17:43 IST" skipped="0">
  <testcase classname="com.ae.qa.testcasesWorkflowAdmin.CataloguePageTestWA" name="validateSubmitReqDefaultCategoryWATest" time="24.792">
    <failure message="Popup Box Message is Failure! expected [null] but found [Success!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Popup Box Message is Failure! expected [null] but found [Success!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.ae.qa.pages.WorkflowAdmin.CataloguePageWA.validateSubmitReqDefaultCategory(CataloguePageWA.java:186)
at com.ae.qa.testcasesWorkflowAdmin.CataloguePageTestWA.validateSubmitReqDefaultCategoryWATest(CataloguePageTestWA.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateSubmitReqDefaultCategoryWATest -->
  <system-out>
    <![CDATA[User logged in successfully
Catalogue Tab is clicked
Workflow whose request needs to be send is selected
Submit request button is clicked
Actual Popup Box:- Success!
Expected Popup Box:- null]]>
  </system-out>
  <testcase classname="com.ae.qa.testcasesWorkflowAdmin.CataloguePageTestWA" name="validateSubmitReqCustomCategoryWATest" time="71.724">
    <failure message="Popup Box Message is Failure! expected [null] but found [Success!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Popup Box Message is Failure! expected [null] but found [Success!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.ae.qa.pages.WorkflowAdmin.CataloguePageWA.validateSubmitReqCustomCategory(CataloguePageWA.java:234)
at com.ae.qa.testcasesWorkflowAdmin.CataloguePageTestWA.validateSubmitReqCustomCategoryWATest(CataloguePageTestWA.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateSubmitReqCustomCategoryWATest -->
  <system-out>
    <![CDATA[User logged in successfully
Workflows Tab is clicked
Import button clicked
assisted Workflow is selected
assisted Workflow is unselected
Create Button is clicked
Priority is set
Expected Completion Time in Seconds is set
Maximum Completion Time in Seconds is set
Cleanup Requests older than Hours fields is set
Manual Execution Time is set
Manual Execution time unit is set
Save button is clicked
Workflow updated
Workflow is enabled successfully
User signed out successfully
User logged in successfully
Catalogue Tab is clicked
Workflow whose request needs to be send is selected
Submit request button is clicked
Actual Popup Box:- Success!
Expected Popup Box:- null]]>
  </system-out>
</testsuite> <!-- com.ae.qa.testcasesWorkflowAdmin.CataloguePageTestWA -->
