<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aedbserver" failures="1" tests="3" name="com.ae.qa.testcasesActivityMonitor.InformationPageTestAM" time="142.363" errors="0" timestamp="2023-04-18T18:40:02 IST" skipped="0">
  <testcase classname="com.ae.qa.testcasesActivityMonitor.InformationPageTestAM" name="validateLastLoginAMTest" time="54.040">
    <failure message="User not created. expected [User created successfully] but found [The username [AMRani1] is taken. Please try another username]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User not created. expected [User created successfully] but found [The username [AMRani1] is taken. Please try another username]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.ae.qa.pagesTenantAdmin.TenantUsersPageTA.valiateCreatingTenantUser(TenantUsersPageTA.java:275)
at com.ae.qa.pages.ActivityMonitor.InformationPageAM.validateLastLoginAM(InformationPageAM.java:65)
at com.ae.qa.testcasesActivityMonitor.InformationPageTestAM.validateLastLoginAMTest(InformationPageTestAM.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validateLastLoginAMTest -->
  <system-out>
    <![CDATA[User log in Successfully
started creating new Tenant
User is created successfully]]>
  </system-out>
  <testcase classname="com.ae.qa.testcasesActivityMonitor.InformationPageTestAM" name="validateViewProfileAMTest" time="53.490"/>
  <system-out>
    <![CDATA[User logged in successfully
Profile details validation successfully.
User signed out successfully]]>
  </system-out>
  <testcase classname="com.ae.qa.testcasesActivityMonitor.InformationPageTestAM" name="validateAboutTabAMTest" time="34.833"/>
  <system-out>
    <![CDATA[User log in successfully
User signed out successfully]]>
  </system-out>
</testsuite> <!-- com.ae.qa.testcasesActivityMonitor.InformationPageTestAM -->
